### ISSUE TITLE
druid关闭连接或预处理语句时出现异常

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/mapresty-rest#83]
druid连接池关闭连接或preparedStatement时会偶发性出现下列异常
```java
[ERROR] 2016-05-18 16:32:33.587 - 释放预处理语句时发生错误:
[ERROR] 2016-05-18 16:32:33.587 - 
java.sql.SQLException: Invalid state, the Connection object is closed.
	at net.sourceforge.jtds.jdbc.TdsCore.checkOpen(TdsCore.java:481)
	at net.sourceforge.jtds.jdbc.TdsCore.clearResponseQueue(TdsCore.java:767)
	at net.sourceforge.jtds.jdbc.JtdsStatement.reset(JtdsStatement.java:722)
	at net.sourceforge.jtds.jdbc.JtdsStatement.close(JtdsStatement.java:966)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.close(JtdsPreparedStatement.java:707)
	at com.alibaba.druid.pool.DruidPooledStatement.close(DruidPooledStatement.java:294)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.closeInternal(DruidPooledPreparedStatement.java:209)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:172)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:201)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.closePreparedStatement(JDBCOperator.java:377)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.execute(JDBCOperator.java:219)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.query(JDBCOperator.java:82)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.query(JDBCOperator.java:43)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.executeLayerQuery(SQLLayerService.java:599)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.queryJson(SQLLayerService.java:394)
	at org.maptalks.gis.rest.layers.data.LayerDataListServlet.postAction(LayerDataListServlet.java:52)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.doPost(RestBaseServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.maptalks.servletrest.servlets.BaseServlet.service(BaseServlet.java:42)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.service(RestBaseServlet.java:43)
	at org.maptalks.gis.rest.MapBaseServlet.service(MapBaseServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.maptalks.servletrest.RestServlet.service(RestServlet.java:70)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1094)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1028)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:445)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] 2016-05-18 16:32:33.587 - recyle error
java.sql.SQLException: Invalid state, the Connection object is closed.
	at net.sourceforge.jtds.jdbc.JtdsConnection.checkOpen(JtdsConnection.java:1744)
	at net.sourceforge.jtds.jdbc.JtdsConnection.clearWarnings(JtdsConnection.java:2068)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:241)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1250)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:292)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:242)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.releaseConnection(JDBCOperator.java:397)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.execute(JDBCOperator.java:220)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.query(JDBCOperator.java:82)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.query(JDBCOperator.java:43)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.executeLayerQuery(SQLLayerService.java:599)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.queryJson(SQLLayerService.java:394)
	at org.maptalks.gis.rest.layers.data.LayerDataListServlet.postAction(LayerDataListServlet.java:52)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.doPost(RestBaseServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.maptalks.servletrest.servlets.BaseServlet.service(BaseServlet.java:42)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.service(RestBaseServlet.java:43)
	at org.maptalks.gis.rest.MapBaseServlet.service(MapBaseServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.maptalks.servletrest.RestServlet.service(RestServlet.java:70)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1094)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1028)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:445)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] 2016-05-18 16:32:33.587 - [EXCEPTION]发生异常:
[ERROR] 2016-05-18 16:32:33.587 - [EXCEPTION]url:http://SGH1PDMIS01:8090/enginerest/rest/databases/x-sde/layers/shape_poc_culture/data?op=query
[ERROR] 2016-05-18 16:32:33.587 - 
java.sql.SQLException: I/O Error: Connection reset
	at net.sourceforge.jtds.jdbc.TdsCore.executeSQL(TdsCore.java:1093)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQLQuery(JtdsStatement.java:493)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeQuery(JtdsPreparedStatement.java:1029)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator$2.doInPreparedStatement(JDBCOperator.java:89)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.execute(JDBCOperator.java:212)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.query(JDBCOperator.java:82)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.query(JDBCOperator.java:43)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.executeLayerQuery(SQLLayerService.java:599)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.queryJson(SQLLayerService.java:394)
	at org.maptalks.gis.rest.layers.data.LayerDataListServlet.postAction(LayerDataListServlet.java:52)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.doPost(RestBaseServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.maptalks.servletrest.servlets.BaseServlet.service(BaseServlet.java:42)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.service(RestBaseServlet.java:43)
	at org.maptalks.gis.rest.MapBaseServlet.service(MapBaseServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.maptalks.servletrest.RestServlet.service(RestServlet.java:70)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1094)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1028)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:445)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at net.sourceforge.jtds.jdbc.SharedSocket.readPacket(SharedSocket.java:850)
	at net.sourceforge.jtds.jdbc.SharedSocket.getNetPacket(SharedSocket.java:731)
	at net.sourceforge.jtds.jdbc.ResponseStream.getPacket(ResponseStream.java:477)
	at net.sourceforge.jtds.jdbc.ResponseStream.read(ResponseStream.java:114)
	at net.sourceforge.jtds.jdbc.ResponseStream.peek(ResponseStream.java:99)
	at net.sourceforge.jtds.jdbc.TdsCore.wait(TdsCore.java:4127)
	at net.sourceforge.jtds.jdbc.TdsCore.executeSQL(TdsCore.java:1086)
	... 32 more
[ERROR] 2016-05-18 16:32:33.602 - [EXCEPTION]发生异常:
[ERROR] 2016-05-18 16:32:33.602 - [EXCEPTION]url:http://SGH1PDMIS01:8090/enginerest/rest/databases/x-sde/layers/shape_poc_culture/data?op=create
[ERROR] 2016-05-18 16:32:33.602 - 
java.sql.SQLException: 不能在具有唯一索引 'INDEX_CULTURE_ROWID' 的对象 'dbo.shape_poc_culture' 中插入重复键的行。
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeUpdate(JtdsPreparedStatement.java:727)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:253)
	at org.maptalks.gis.dao.service.sql.jdbc.JDBCOperator.insertAndGetKey(JDBCOperator.java:172)
	at org.maptalks.gis.dao.service.sql.SQLLayerService.add(SQLLayerService.java:106)
	at org.maptalks.gis.rest.layers.data.LayerDataListServlet.createLayerData(LayerDataListServlet.java:162)
	at org.maptalks.gis.rest.layers.data.LayerDataListServlet.postAction(LayerDataListServlet.java:38)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.doPost(RestBaseServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.maptalks.servletrest.servlets.BaseServlet.service(BaseServlet.java:42)
	at org.maptalks.gis.modules.commons.servlet.RestBaseServlet.service(RestBaseServlet.java:43)
	at org.maptalks.gis.rest.MapBaseServlet.service(MapBaseServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.maptalks.servletrest.RestServlet.service(RestServlet.java:70)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1094)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1028)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:445)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by FuZhenn** [comment]
该问题应该已在新版druid中解决
https://github.com/alibaba/druid/pull/1102
